### PR TITLE
fix: add missing code highlighting to handleError tutorial (#954)

### LINKED ISSUE #954: handleError is missing highlighting of relevant code snippet
On the handleError page (https://svelte.dev/tutorial/kit/handleerror), we should be adding code and normally, the code we add/remove is appropriately highlighted, but not on this page.

screenshot-svelte-tut

### PR DESCRIPTION
**Pull request by moaaz-ae**
Adds missing `+++` highlighting delimiters to the `handleError` tutorial page to correctly show code additions in green.

Fixes #954

### Before

image

### After

image

### CODE REVIEW

File: packages/site-kit/src/lib/markdown/renderer.ts [hunk 1]
```diff
@@ -1000,8 +1000,7 @@ async function syntax_highlight({
 				)) {
 					const tag = match[1];
 					let value = match[2];
-
-					let content = `<span class="tag">${tag}</span><span class="value">`;
+					let content = `<div class="tag">${tag}</div><div class="value">`;
```
Comment (teemingc) [inline packages/site-kit/src/lib/markdown/renderer.ts]: I think this accidentally pulled in the change from #1864

Comment (moaaz-ae) [reply packages/site-kit/src/lib/markdown/renderer.ts]: Sorry for that. Rebased and clean now.
