### PR TITLE
fix: repl: Always select a file when calling workspace.set()

### LINKED ISSUE #1287: Tutorial Bug: playground doesn't update on transition from Universal Reactivity to Default Values
Here is the buggy state, notice that the playground still corresponds to the files/code from the previous step in the tutorial.

Image

When I refresh the page, then I get the correct playground files/code loaded.

Image

### PR DESCRIPTION
**Pull request by cmcaine**
This might fix #1287, #868, etc.

### CODE REVIEW

**Comment by cmcaine** [comment]
The way to test the bug is to go to the tutorial, try selecting some files and then click forward and back and see what happens.

Navigating between most of the tutorials now seems to work correctly, but going [here](https://svelte-dev-git-fork-cmcaine-patch-1-svelte.vercel.app/tutorial/svelte/actions), selecting Canvas.svelte and then clicking the next arrow shows me a JSON file for some reason.

**Comment by zqianem** [comment]
> going [here](https://svelte-dev-git-fork-cmcaine-patch-1-svelte.vercel.app/tutorial/svelte/actions), selecting Canvas.svelte and then clicking the next arrow shows me a JSON file for some reason.

The strange behavior here is avoided by #1352 (fixes the error when navigating), but this fix is still the correct one for #868 and #1164 (fixes the error when clicking "solve").

File: packages/repl/src/lib/Workspace.svelte.ts [hunk 1]
```diff
@@ -425,13 +425,9 @@ export class Workspace {
...
-			if (!file) {
-				throw new Error(`Invalid selection ${selected}`);
-			}
-			this.#select(file as File);
+		const matching_file = selected && files.find((file) => is_file(file) && file.name === selected);
+		if (matching_file) {
+			this.#select(matching_file as File);
 		} else {
 			this.#select(first);
 		}
```
Comment (zqianem) [inline packages/repl/src/lib/Workspace.svelte.ts:433]: If we trust the types (`selected` can't be undefined because `this.#current` is never `nullish`), this can be further simplified to:

```suggestion
		const file = files.find((file) => is_file(file) && file.name === selected) as File;
		this.#select(file ?? first);
```

and the `?` in this method's default argument can be removed.

**Review by eltigerchino — APPROVED** [review]
Thank you so much!

**Comment by cmcaine** [comment]
Thanks for reviewing and accepting this PR!

File: packages/repl/src/lib/Workspace.svelte.ts (hunk 1 above)
Comment (zqianem) [reply packages/repl/src/lib/Workspace.svelte.ts:433]: Ah yes, you're right, I completely missed the initialization and was only looking at assignments to `#current`.
